# Generated by Django 3.2.8 on 2021-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_created_data_post_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='cover2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='l_heading',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='l_heading_text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='s_heading',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='s_heading_text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_1',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_2',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_3',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
